global:
  proxy:
    policy: disabled

grafana:
  enabled: true

ingress:
  enabled: false
gateways:
  enabled: false
sidecarInjectorWebhook:
  enabled: false
galley:
  enabled: false
mixer:
  enabled: false
pilot:
  enabled: false
prometheus:
  enabled: false
zipkin:
  enabled: false
servicegraph:
  enabled: false
tracing:
  enabled: false
kiali:
  enabled: false
