global:
  proxy:
    autoInject: disabled
    privileged: true
  multiCluster:
    enabled: false

security:
  enabled: true
  cleanUpOldCA: false

ingress:
  autoscaleMin: 0
  autoscaleMax: 0
ingressgateway:
  autoscaleMin: 0
  autoscaleMax: 0
egressgateway:
  autoscaleMin: 0
  autoscaleMax: 0

gateways:
  istio-egressgateway:
    autoscaleMin: 0
    autoscaleMax: 0
  istio-ingressgateway:
    autoscaleMin: 0
    autoscaleMax: 0

mixer:
  autoscaleMin: 0
  autoscaleMax: 0

  policy:
    autoscaleEnabled: false

  telemetry:
    autoscaleEnabled: false

pilot:
  autoscaleMin: 0
  autoscaleMax: 0
  traceSampling: 100.0
