---
# Source: istio/charts/mixer/templates/poddisruptionbudget.yaml
# Source: istio/charts/kiali/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio-1-1-0-snapshot-6
data:
  config.yaml: |
    istio_namespace: istio-system
    istio_namespace: ISTIO_NAMESPACE
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console
    external_services:
      jaeger:
        url: JAEGER_URL
      grafana:
        url: GRAFANA_URL
    identity:
      cert_file: /kiali-cert/tls.crt
      private_key_file: /kiali-cert/tls.key

---
# Source: istio/templates/sidecar-injector-configmap.yaml
# Source: istio/charts/kiali/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-service-account
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio-1-1-0-snapshot-6

---
# Source: istio/charts/mixer/templates/serviceaccount.yaml
# Source: istio/charts/security/templates/cleanup-secrets.yaml
# Source: istio/charts/security/templates/serviceaccount.yaml
# Source: istio/templates/serviceaccount.yaml
# Source: istio/charts/kiali/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio-1-1-0-snapshot-6
rules:
- apiGroups: ["", "apps", "autoscaling", "batch"]
  resources:
  - configmaps
  - cronjobs
  - deployments
  - endpoints
  - horizontalpodautoscalers
  - jobs
  - namespaces
  - nodes
  - pods
  - projects
  - services
  - statefulsets
  - replicasets
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["project.openshift.io"]
  resources:
  - projects
  verbs:
  - get
- apiGroups: ["route.openshift.io"]
  resources:
  - routes
  verbs:
  - get
- apiGroups: ["apps.openshift.io"]
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups: ["config.istio.io"]
  resources:
  - apikeys
  - authorizations
  - checknothings
  - circonuses
  - deniers
  - fluentds
  - handlers
  - kubernetesenvs
  - kuberneteses
  - listcheckers
  - listentries
  - logentries
  - memquotas
  - metrics
  - opas
  - prometheuses
  - quotas
  - quotaspecbindings
  - quotaspecs
  - rbacs
  - reportnothings
  - rules
  - solarwindses
  - stackdrivers
  - statsds
  - stdios
  verbs:
  - delete
  - get
  - list
  - patch
  - patch
  - watch
  - delete
- apiGroups: ["networking.istio.io"]
  resources:
  - destinationrules
  - gateways
  - serviceentries
  - virtualservices
  verbs:
  - delete
  - get
  - list
  - patch
  - patch
  - watch
  - delete

---
# Source: istio/charts/mixer/templates/clusterrole.yaml
# Source: istio/charts/security/templates/clusterrole.yaml
# Source: istio/templates/clusterrole.yaml
# Source: istio/charts/kiali/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-kiali-admin-role-binding-istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio-1-1-0-snapshot-6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali
subjects:
- kind: ServiceAccount
  name: kiali-service-account
  namespace: istio-system

---
# Source: istio/charts/mixer/templates/clusterrolebinding.yaml
# Source: istio/charts/security/templates/clusterrolebinding.yaml
# Source: istio/templates/clusterrolebinding.yaml
# Source: istio/charts/kiali/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: kiali-cert-secret
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio-1-1-0-snapshot-6
spec:
  ports:
  - name: http-kiali
    protocol: TCP
    port: 20001
  selector:
    app: kiali

---
# Source: istio/charts/mixer/templates/service.yaml
# Source: istio/charts/security/templates/service.yaml
# Source: istio/charts/kiali/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio-1-1-0-snapshot-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali
  template:
    metadata:
      name: kiali
      labels:
        app: kiali
        chart: kiali
        heritage: Tiller
        release: istio-1-1-0-snapshot-6
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: kiali-service-account
      containers:
      - image: "kiali/kiali:v0.13.0"
        name: kiali
        command:
        - "/opt/kiali/kiali"
        - "-config"
        - "/kiali-configuration/config.yaml"
        - "-v"
        - "4"
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVER_CREDENTIALS_USERNAME
          valueFrom:
            secretKeyRef:
              name: kiali
              key: username
        - name: SERVER_CREDENTIALS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kiali
              key: passphrase
        volumeMounts:
        - name: kiali-configuration
          mountPath: "/kiali-configuration"
        - name: kiali-cert
          mountPath: "/kiali-cert"
        resources:
          requests:
            cpu: 10m
          
      volumes:
      - name: kiali-configuration
        configMap:
          name: kiali
      - name: kiali-cert
        secret:
          secretName: kiali-cert-secret
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x

---
# Source: istio/charts/mixer/templates/deployment.yaml
# Source: istio/charts/security/templates/deployment.yaml
# Source: istio/charts/security/templates/enable-mesh-permissive.yaml
# Source: istio/charts/mixer/templates/autoscale.yaml
# Source: istio/charts/kiali/templates/demosecret.yaml


---
# Source: istio/charts/kiali/templates/gateway.yaml


---
# Source: istio/charts/kiali/templates/ingress.yaml

---
# Source: istio/charts/kiali/templates/tests/test-kiali-connection.yaml


---
# Source: istio/charts/security/templates/enable-mesh-mtls.yaml
# Source: istio/charts/security/templates/meshexpansion.yaml
# Source: istio/charts/security/templates/tests/test-citadel-connection.yaml
# Source: istio/templates/configmap.yaml
# Source: istio/templates/endpoints.yaml
# Source: istio/templates/install-custom-resources.sh.tpl
# Source: istio/templates/service.yaml
# Source: istio/charts/mixer/templates/config.yaml
