---
- name: Create kiali secret
  command: "{{ openshift_client_binary }} create secret generic {{ openshift_istio_kiali_secret }} -n {{ openshift_istio_namespace }}  --from-literal=username={{ openshift_istio_kiali_username }} --from-literal=passphrase={{ openshift_istio_kiali_password }}"

- name: Get Grafana host
  command: "{{ openshift_client_binary }} get route grafana -o 'jsonpath={.spec.host}'"
  register: grafana_url

- name: Update Grafana URL
  replace:
    path: "{{ openshift_kiali_yaml }}"
    regexp: "GRAFANA_URL"
    replace: "http://{{ grafana_url.stdout }}"

- name: Get Jaeger host
  command: "{{ openshift_client_binary }} get route jaeger-query -o 'jsonpath={.spec.host}'"
  register: jaeger_url

- name: Update Jaeger URL
  replace:
    path: "{{ openshift_kiali_yaml }}"
    regexp: "JAEGER_URL"
    replace: "https://{{ jaeger_url.stdout }}"

- name: Update Istio namespace
  replace:
    path: "{{ openshift_kiali_yaml }}"
    regexp: "ISTIO_NAMESPACE"
    replace: "{{ openshift_istio_namespace }}"

- name: Update Kiali Version
  replace:
    path: "{{ openshift_kiali_yaml }}"
    regexp: "KIALI_VERSION"
    replace: "{{ openshift_istio_kiali_image_version }}"

- name: Add Kiali CRDs
  command: "{{ openshift_client_binary }} create -f {{ openshift_kiali_crds_yaml }} -n {{ openshift_istio_namespace }}"

- name: Wait for resource CRDs to establish
  shell: "{{ openshift_client_binary }} get --raw /apis/{{ item.group }}/{{ item.version }}/{{ item.name }}"
  register: result
  until: result.rc == 0
  retries: 10
  delay: 2
  ignore_errors: yes
  with_items: "{{ openshift_kiali_resources }}"

- name: Add Kiali dashboard components
  command: "{{ openshift_client_binary }} create -f {{ openshift_kiali_dashboards_yaml }} -n {{ openshift_istio_namespace }}"

- name: Add Kiali components
  command: "{{ openshift_client_binary }} create -f {{ openshift_kiali_yaml }} -n {{ openshift_istio_namespace }}"

- name: Check kiali route exists
  command: "{{ openshift_client_binary }} get route kiali -n {{ openshift_istio_namespace }}"
  register: kiali_route
  ignore_errors: yes

- name: Expose kiali service
  command: "{{ openshift_client_binary }} create route reencrypt kiali --service=kiali -n {{ openshift_istio_namespace }}"
  when: kiali_route != 0
