---
- name: Initialise 3scale parameters
  set_fact:
    threescale_parameters:
      "PARAM_THREESCALE_LISTEN_ADDR": "{{threescale_adapter_listenAddr}}"
      "PARAM_THREESCALE_LOG_LEVEL": "{{threescale_adapter_logLevel}}"
      "PARAM_THREESCALE_LOG_JSON": "{{threescale_adapter_logJSON}}"
      "PARAM_THREESCALE_REPORT_METRICS": "{{threescale_adapter_reportMetrics}}"
      "PARAM_THREESCALE_METRICS_PORT": "{{threescale_adapter_metricsPort}}"
      "PARAM_THREESCALE_CACHE_TTL_SECONDS": "{{threescale_adapter_cacheTTLSeconds}}"
      "PARAM_THREESCALE_CACHE_REFRESH_SECONDS": "{{threescale_adapter_cacheRefreshSeconds}}"
      "PARAM_THREESCALE_CACHE_ENTRIES_MAX": "{{threescale_adapter_cacheEntriesMax}}"
      "PARAM_THREESCALE_CACHE_REFRESH_RETRIES": "{{threescale_adapter_cacheRefreshRetries}}"
      "PARAM_THREESCALE_ALLOW_INSECURE_CONN": "{{threescale_adapter_allowInsecureConn}}"
      "PARAM_THREESCALE_CLIENT_TIMEOUT_SECONDS": "{{threescale_adapter_clientTimeoutSeconds}}"

- name: Modify 3scale parameters in configuration file {{ openshift_threescale_yaml }}
  replace:
    path: "{{ openshift_threescale_yaml }}"
    regexp: "{{ item.key }}"
    replace: "{{ item.value }}"
  with_dict: "{{ threescale_parameters }}"

- name: Add 3scale components
  command: "{{ openshift_client_binary }} create -f {{ openshift_threescale_yaml }} -n {{ openshift_istio_namespace }}"

- name: Add 3scale authorization template
  command: "{{ openshift_client_binary }} create -f {{ openshift_threescale_authorization_template_yaml }} -n {{ openshift_istio_namespace }}"

- name: Add 3scale adapter
  command: "{{ openshift_client_binary }} create -f {{ openshift_threescale_adapter_yaml }} -n {{ openshift_istio_namespace }}"
