---
- name: Create kiali secret
  command: "{{ openshift_client_binary }} create secret generic {{ openshift_istio_kiali_secret }} -n {{ openshift_istio_namespace }}  --from-literal=username={{ openshift_istio_kiali_username }} --from-literal=passphrase={{ openshift_istio_kiali_password }}"

- name: Add Kiali components
  command: "{{ openshift_client_binary }} create -f {{ openshift_kiali_yaml }} -n {{ openshift_istio_namespace }}"

- name: Check kiali route exists
  command: "{{ openshift_client_binary }} get route kiali -n {{ openshift_istio_namespace }}"
  register: kiali_route
  ignore_errors: yes

- name: Expose kiali service
  command: "{{ openshift_client_binary }} create route edge kiali --service=kiali -n {{ openshift_istio_namespace }}"
  when: kiali_route != 0
